---

sudo: required
dist: bionic
language: generic

git:
  depth: 10

script:
    - ln -s ~/zlalanne/dotfiles ~/.dotfiles
    - travis_wait ./bootstrap.sh
    - travis_wait ./deploy.sh
    - travis_wait ./bin/.bin/dotfiles_update
