#+TITLE: dotfiles

[[https://travis-ci.org/zlalanne/dotfiles][https://travis-ci.org/zlalanne/dotfiles.svg?branch=master]]

** Description

  My collection of dotfiles. My primary development machines right now run KDE
  Neon which is based on Ubuntu 18.04. So the =bootstrap.sh= and =deploy.sh=
  scripts have some dependencies on debian/Ubuntu.
  
  Package installation is done in =boostrap.sh=, mostly used to setup tools
  needed for developing code. The =deploy.sh= script handles symlinking all the
  dotfiles to their correct destinations.
  
  My main editor is Emacs using [[http://spacemacs.org/][Spacemacs]]. My main shell is zsh using [[https://ohmyz.sh/][Oh-My-Zsh]].

** Issues

 * [ ] Better org-mode settings
 * [ ] Emoji's not always working with magit buffers
 * [ ] Fix xresources issues with KDE Neon
 * [ ] Minimize vimrc to be usable now that I'm on emacs (maybe try to nvim)
 * [ ] Spacemacs recentf issue [[https://github.com/syl20bnr/spacemacs/issues/5186]]
 * [X] Add better printing / clean up =deploy.sh= and =bootstrap.sh= scripts to hide stderr
 * [X] Add some spacemcas/emacs CI checks
 * [X] Always use shellcheck checker in shell-script-mode. bashate seems broken at the moment
 * [X] Better symbolic link checking in deploy.sh script
 * [X] Move spacemacs layers back to repo? And add them as custom path to .spacemacs?
 * [X] Working markdown preview in Spacemacs
 * [X] Working travis.ci setup again

*** Bazel Spacemacs Layer

 * [ ] Better build/test/run support in Bazel Spacemacs layer
 * [ ] Some python keywords missing from bazel-mode
 * [X] Bazel Spacemacs layer could use better indention when editing

** Post-Install Steps

There are a few steps to run manually after setting up the first time.

#+BEGIN_SRC elisp
  ;; Run some elisp functions
  (all-the-icons-install-fonts)
  (emojify-download-emoji)
#+END_SRC
