---
# Install webdev related packages

- name: Install webdev related items
  apt:
    name={{item}}
    state=latest
  with_items:
    - nodejs
    - npm
    - firefox
    - sqlite3
  sudo: yes

- name: Install global NPM modules
  npm:
    name={{item}}
    global=yes
    state=latest
  with_items:
    - bower
    - typescript
    - grunt
    - gulp
  sudo: yes

# Install Virtualbox
- include: virtualbox.yml

# Install Vagrant
- include: vagrant.yml
