---
# Configure machine to work with Juniper Network connect on a 64bit Linux box

- name: Check if 32bit java is installed
  stat: path=/usr/bin/java32
  register: java32_check

- name: Create java32 directory
  file:
    path=/usr/bin/java32
    state=directory
  sudo: yes
  when: not java32_check.stat.exists

- name: Download 32 bit JRE from Oracle
  shell: 'wget --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" "{{jre_url}}" -O /tmp/jre-{{jre_major_update}}-linux-i586.tar.gz '
  when: not java32_check.stat.exists

- name: Extract 32 bit JRE
  unarchive:
    src=/tmp/jre-{{jre_major_update}}-linux-i586.tar.gz
    dest=/usr/bin/java32
    copy=no
  sudo: yes
  when: not java32_check.stat.exists

- name: Set 32bit JRE as alternative to java
  shell: 'update-alternatives --install /usr/bin/java java /usr/bin/java32/{{jre_install_folder}}/bin/java -10'
  sudo: yes

- name: Install network connect dependencies
  apt:
    name={{item}}
    state=present
  with_items:
    - libstdc++6:i386
    - lib32z1
    - lib32ncurses5
    - lib32bz2-1.0
    - libxext6:i386
    - libxrender1:i386
    - libxtst6:i386
    - libxi6:i386
    - xterm
  sudo: yes

- name: Create update-alternatives symlink
  file:
    src=/usr/bin/update-alternatives
    dest=/usr/sbin/update-alternatives
    state=link
  sudo: yes

