---
# Install applications related to i3

- name: Install i3 applications
  apt:
    name={{item}}
    state=latest
  with_items:
    - rxvt-unicode-256color
    - arandr
    - feh
    - lxappearance
    - unclutter
    - compton
    - autocutsel
    - zathura
  become: yes

# TODO: need a better way to save results to see if changes occur

- name: Download applications
  git:
    repo='https://github.com/{{item.username}}/{{item.app}}.git'
    dest='/home/{{ansible_user_id}}/Projects/apps/{{item.app}}'
    version='{{item.branch}}'
    depth=1
  with_items: '{{apps}}'
  register: app_results

- name: Configure applications
  command: ./configure
  args:
    chdir: '/home/{{ansible_user_id}}/Projects/apps/{{item.app}}'
  ignore_errors: True
  with_items: '{{apps}}'

- name: Build applications
  command: make clean all
  args:
    chdir: '/home/{{ansible_user_id}}/Projects/apps/{{item.app}}'
  with_items: '{{apps}}'

- name: Install applications
  command: make install
  args:
    chdir: '/home/{{ansible_user_id}}/Projects/apps/{{item.app}}'
  with_items: '{{apps}}'
  become: yes

