---
# Install applications related to i3

- name: Install i3 applications
  apt:
    name={{item}}
    state=latest
  with_items:
    - rxvt-unicode-256color
    - arandr
    - feh
    - lxappearance
    - unclutter
    - compton
    - autocutsel
  become: yes

- name: Download applications
  git:
    repo='https://github.com/{{item.username}}/{{item.app}}.git'
    dest=/home/{{ansible_user_id}}/Projects/apps/{{item.app}}
    depth=1
  with_items: apps
