---
# Install applications related to i3

- name: Install i3 applications
  apt:
    name={{item}}
    state=latest
  with_items:
    - rxvt-unicode-256color
    - arandr
    - feh
    - lxappearance
    - unclutter
    - compton
    - autocutsel
    - zathura
  become: yes

# TODO: need a better way to save results to see if changes occur

- include: i3blocks.yml

