---
# Install applications related to i3

- name: Install i3 applications
  apt:
    name={{item}}
    state=latest
  with_items:
    - rxvt-unicode-256color
    - arandr
    - feh
    - lxappearance
    - unclutter
    - compton
    - autocutsel
  become: yes

- name: Download applications
  git:
    repo='https://github.com/{{item.username}}/{{item.app}}.git'
    dest=/home/{{ansible_user_id}}/Projects/apps/{{item.app}}
    depth=1
  with_items: apps
  register: {{item.app}}_git

- name: Build i3blocks
  command: make clean all
  args:
    chdir: /home/{{ansible_user_id}}/Projects/apps/i3blocks
  when: i3blocks.git.changed

- name: Install i3blocks
  command: make install
  args:
    chdir: /home/{{ansible_user_id}}/Projects/apps/i3blocks
  when: i3blocks.git.changed
  become: yes

