---
# Install i3gaps from source

- name: Clone git repository
  git:
    repo=https://github.com/Airblader/i3.git
    depth=1
    dest='/home/{{ansible_user_id}}/Projects/apps/i3-gaps'
    version=gaps
  register: i3gaps_git

- name: Build i3gaps
  command: make
  args:
    chdir: '/home/{{ansible_user_id}}/Projects/apps/i3-gaps'
  when: i3gaps_git.changed

- name: Install i3blocks
  command: make install
  args:
    chdir: '/home/{{ansible_user_id}}/Projects/apps/i3-gaps'
  become: yes
  when: i3gaps_git.changed

