---
# Install i3gaps from source

- name: Ensure i3 build dependencies
  apt:
    name={{item}}
  with_items:
    - libxcb1-dev
    - libxcb-keysyms1-dev
    - libpango1.0-dev
    - libxcb-util0-dev
    - libxcb-icccm4-dev
    - libyajl-dev
    - libstartup-notification0-dev
    - libxcb-randr0-dev
    - libev-dev
    - libxcb-cursor-dev
    - libxcb-xinerama0-dev
    - libxcb-xkb-dev
    - libxkbcommon-dev
    - libxkbcommon-x11-dev
  become: yes

- name: Clone git repository
  git:
    repo=https://github.com/Airblader/i3.git
    dest='/home/{{ansible_user_id}}/Projects/apps/i3-gaps'
    version=gaps
  register: i3gaps_git

- name: Build i3gaps
  command: make
  args:
    chdir: '/home/{{ansible_user_id}}/Projects/apps/i3-gaps'
  when: i3gaps_git.changed

- name: Install i3blocks
  command: make install
  args:
    chdir: '/home/{{ansible_user_id}}/Projects/apps/i3-gaps'
  become: yes
  when: i3gaps_git.changed or i3apt.changed

