---
# Install pa-applet from source

- name: Ensure pa-applet dependencies installed
  apt:
    name={{item}}
  with_items:
    - libglib2.0-dev
    - libgtk-3-dev
    - libnotify-dev
    - libpulse-dev
    - libx11-dev
    - automake
    - autoconf
    - pkg-config
  become: yes

- name: Download pa-applet
  git:
    repo=https://github.com/zlalanne/pa-applet.git
    dest=/home/{{ansible_user_id}}/Projects/apps/pa-applet
    depth=1
  register: paapplet_git

- name: Run autogen
  command: ./autogen.sh
  args:
    chdir: '/home/{{ansible_user_id}}/Projects/apps/pa-applet'
  when: paapplet_git.changed

- name: Run configure
  command: ./configure
  args:
    chdir: '/home/{{ansible_user_id}}/Projects/apps/pa-applet'
  when: paapplet_git.changed

- name: Build pa-applet
  command: make clean all
  args:
    chdir: '/home/{{ansible_user_id}}/Projects/apps/pa-applet'
  when: paapplet_git.changed

- name: Install pa-applet
  command: make install
  args:
    chdir: '/home/{{ansible_user_id}}/Projects/apps/pa-applet'
  when: paapplet_git.changed
  become: yes
