---
# Install i3blocks from source

- name: Ensure rofi dependencies installed
  apt:
    name={{item}}
  with_items:
    - libxinerama-dev
    - libxft2-dev
    - libpango1.0-dev
    - libpangocairo-1.0-0
    - libcairo2-dev
    - libglib2.0-dev
    - libx11-dev
    - libstartup-notification0-dev
  become: yes

- name: Download rofi
  unarchive:
    src={{rofi_url}}
    dest='/home/{{ansible_user_id}}/Projects/apps'
    copy=no
  register: rofi_tar

- name: Configure rofi
  command: ./configure
  args:
    chdir: '/home/{{ansible_user_id}}/Projects/apps/rofi-{{rofi_version}}'
  when: rofi_tar.changed

- name: Build rofi
  command: make
  args:
    chdir: '/home/{{ansible_user_id}}/Projects/apps/rofi-{{rofi_version}}'
  when: rofi_tar.changed

- name: Install rofi
  command: make install
  args:
    chdir: '/home/{{ansible_user_id}}/Projects/apps/rofi-{{rofi_version}}'
  become: yes
  when: rofi_tar.changed

