---
# Install i3gaps from source

- name: Ensure i3 build dependencies
  apt:
    name={{item}}
  with_items:
    - libxi-dev
  become: yes

- name: Clone git repository
  git:
    repo=https://github.com/Airblader/unclutter-xfixes.git
    dest='/home/{{ansible_user_id}}/Projects/apps/unclutter'
  register: unclutter_git

- name: Build unclutter
  command: make clean unclutter
  args:
    chdir: '/home/{{ansible_user_id}}/Projects/apps/unclutter'
  when: unclutter_git.changed

- name: Install unclutter
  command: make install
  args:
    chdir: '/home/{{ansible_user_id}}/Projects/apps/unclutter'
  become: yes
  when: unclutter_git.changed

