---
- name: Install Chromium browser
  apt:
    name={{item}}
    state=latest
  with_items:
    - chromium-browser
    - chromium-browser-l10n
    - chromium-codecs-ffmpeg-extra
  become: yes

- name: Add Google repo key
  apt_key:
    url=https://dl-ssl.google.com/linux/linux_signing_key.pub
    state=present
  become: yes

- name: Add Chrome PPA
  lineinfile:
    create=yes
    dest=/etc/apt/sources.list.d/google-chrome.list
    line="deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
  become: yes

- name: Install Chrome stable
  apt:
    update_cache=yes
    name=google-chrome-stable
    state=latest
  become: yes
