---
# Install IDEA

- name: Check if IntelliJ IDEA installed
  stat: path=/opt/jetbrains/idea-IC-{{idea_full_version}}/bin/idea.sh
  register: idea_check

- name: Create Jetbrains installation directory
  file:
    path=/opt/jetbrains
    state=directory
  sudo: yes
  when: not idea_check.stat.exists

- name: Download IntelliJ IDEA installer
  get_url:
    url=https://download.jetbrains.com/idea/ideaIC-{{idea_version}}.tar.gz
    dest=/tmp
    validate_certs=no
  when: not idea_check.stat.exists

- name: Extract IDEA tar.gz
  unarchive:
    src=/tmp/ideaIC-{{idea_version}}.tar.gz
    dest=/opt/jetbrains
    copy=no
  sudo: yes
  when: not idea_check.stat.exists

- name: Adding hidpi to idea
  lineinfile:
    dest={{item}}
    state=present
    line='-Dhidpi=true'
  sudo: yes
  with_items:
    - '/opt/jetbrains/idea-IC-{{idea_full_version}}/bin/idea.vmoptions'
    - '/opt/jetbrains/idea-IC-{{idea_full_version}}/bin/idea64.vmoptions'
  when: hidpi
