#!/usr/bin/env bash
#
# Setup for a Linux laptop. Currently a Lenovo ThinkPad X1 Carbon 2015

cd ..
stow atom
stow bin
stow git
stow gtk
stow i3
stow tmux
stow urxvt
stow vim
stow zsh

cd playbook
ansible-playbook -i hosts machines.yml
