#!/usr/bin/env bash
#
# Setup for a Linux Desktop

set -o errexit
set -o nounset
set -o pipefail

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Remove old files
rm -rf ~/.zshrc

# Link dotfiles
stow -t ~/ atom
stow -t ~/ bin
stow -t ~/ compton
stow -t ~/ git
# Stow ignores .gitignore files, need to link this manually
rm -f ~/.gitignore
ln -s "${__dir}/../git/.gitignore" ~/.gitignore
stow -t ~/ gtk
stow -t ~/ i3
stow -t ~/ ranger
stow -t ~/ tmux
stow -t ~/ urxvt
stow -t ~/ vim
stow -t ~/ zathura
stow -t ~/ zsh

# Run installation
cd "${__dir}/../playbook"
ansible-playbook -i hosts personal_linux_desktop.yml
