---
# Installing Eagle

- name: Check for Eagle installation
  stat: path=/opt/eagle/eagle-{{eagle_version_full}}/bin/eagle
  register: eagle_check

- name: Create Eagle installation folder
  file:
    path=/opt/eagle
    state=directory
  sudo: yes

- name: Download Eagle installer
  get_url:
    url={{eagle_url}}
    dest=/tmp/eagle-lin64-{{eagle_version_full}}.run
    mode=0775
  when: not eagle_check.stat.exists

- name: Run Eagle installer
  command: /tmp/eagle-lin64-{{eagle_version_full}}.run /opt/eagle/
  when: not eagle_check.stat.exists
  sudo: yes

- name: Create Eagle .desktop file
  template:
    src=eagle.desktop.j2
    dest=/usr/share/applications/eagle.desktop
    owner=root
    group=root
    mode=0644
  sudo: yes
