---
# Installing common things

- name: Add PPAs
  apt_repository:
    repo={{item}}
    state=present
    update_cache=yes
  with_items:
    - ppa:git-core/ppa
  become: yes

- name: Install packages
  apt:
    name={{item}}
    state=latest
  with_items:
    - vim-gtk
    - zsh
    - tmux
    - htop
    - git
    - unrar
    - cmake
    - build-essential
    - python-dev
    - xclip
    - ranger
    - highlight
    - dos2unix
    - curl
    - nfs-common
  become: yes

- name: Installing vundle
  git:
    repo=https://github.com/gmarik/Vundle.vim.git
    dest=~/.vim/bundle/Vundle.vim

- name: Installing YouCompleteMe
  git:
    repo=https://github.com/Valloric/YouCompleteMe.git
    dest=~/.vim/bundle/YouCompleteMe
    update=yes
    depth=1
  register: ycm_git

- name: Compile YouCompleteMe
  command: ./install.py --clang-completer
  args:
    chdir: /home/{{ansible_user_id}}/.vim/bundle/YouCompleteMe
  when: ycm_git.changed

- name: Install vim plugins
  command: vim +PluginInstall +qall

- name: Ensure projects directory exists
  file:
    path=/home/{{ansible_user_id}}/Projects/{{item}}
    state=directory
  with_items:
    - fonts
    - apps

- name: Add powerline fonts
  git:
    repo=https://github.com/powerline/fonts.git
    dest=/home/{{ansible_user_id}}/Projects/fonts/powerline-fonts
    depth=1
  register: fonts_git

- name: Install powerline fonts
  command: ./install.sh
  args:
    chdir: /home/{{ansible_user_id}}/Projects/fonts/powerline-fonts
  when: fonts_git.changed

- name: Install tmux plugin manager
  git:
    repo=https://github.com/tmux-plugins/tpm
    dest=~/.tmux/plugins/tpm
    depth=1

- name: Install tmux plugins
  command: ./install_plugins all
  args:
    chdir: /home/{{ansible_user_id}}/.tmux/plugins/tpm/bin

- name: Update tmux plugins
  command: ./update_plugins all
  args:
    chdir: /home/{{ansible_user_id}}/.tmux/plugins/tpm/bin

- name: Install oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh.git
    depth=1
    dest=~/.oh-my-zsh

- name: Ensure shell is zsh
  user:
    name={{ansible_user_id}}
    shell=/usr/bin/zsh
  become: yes
  when: change_shell

- name: Ensure lightdm config folder is present
  file:
    path=/etc/lightdm/lightdm.conf.d
    state=directory
  become: yes
  when: configure_login_manager

- name: Copy screenlayout to config directory
  copy:
    src=screenlayouts/{{ screenlayout }}
    dest=/etc/lightdm/lightdm.conf.d/{{ screenlayout }}
    mode=0700
  become: yes
  when: configure_login_manager

- name: Copy lightdm config to directory
  template:
    src=50-xrandrconfig.conf.j2
    dest=/etc/lightdm/lightdm.conf.d/50-xrandrconfig.conf
  become: yes
  when: configure_login_manager
