---
# Installing common things

- name: Add PPAs
  apt_repository:
    repo={{item}}
    state=present
    update_cache=yes
  with_items:
    - ppa:git-core/ppa
  sudo: yes

- name: Install packages
  apt:
    name={{item}}
    state=latest
  with_items:
    - vim
    - zsh
    - tmux
    - htop
    - git
    - unrar
    - cmake
    - build-essential
    - python-dev
  sudo: yes

- name: Installing vundle
  git:
    repo=https://github.com/gmarik/Vundle.vim.git
    dest=~/.vim/bundle/Vundle.vim

- name: Installing YouCompleteMe
  git:
    repo=https://github.com/Valloric/YouCompleteMe.git
    dest=~/.vim/bundle/YouCompleteMe
    update=yes
  register: ycm_git

- name: Compile YouCompleteMe
  command: ./install.sh --clang-completer
  args:
    chdir: /home/{{username}}/.vim/bundle/YouCompleteMe
  when: ycm_git.changed

- name: Install vim plugins
  command: vim +PluginInstall +qall

- name: Install oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh.git
    dest=~/.oh-my-zsh

- name: Change default shell to zsh
  user:
    name={{username}}
    shell=/usr/bin/zsh
  sudo: yes
