---
# Install tools for laptops

- name: Add TLP repository
  apt_repository:
    repo='ppa:linrunner/tlp'
    state=present
  sudo: yes

- name: Install TLP
  apt:
    name={{item}}
    update_cache=yes
    state=latest
  sudo: yes
  with_items:
    - tlp
    - tlp-rdw

- name: Install extra lenovo tools
  apt:
    name={{item}}
    update_cache=yes
    state=latest
  sudo: yes
  with_items:
    - tp-smapi-dkms
    - acpi-call-dkms
  when: lenovo 

