---
# Install python development tools

- name: Install python related packages
  apt:
    name={{item}}
    state=latest
  with_items:
    - python-dev
    - python3-dev
    - python-setuptools
    - python3-setuptools
  sudo: yes

- name: Install pip
  easy_install:
    name=pip
  sudo: yes

- name: Install pip3
  easy_install:
    name=pip
    executable=easy_install3
  sudo: yes

- name: Install some python2 modules globally
  pip:
    name={{item}}
    state=latest
    executable=pip2
  with_items:
    - virtualenv
    - bpython
    - virtualenvwrapper
    - pep8
  sudo: yes

- name: Install some python3 modules globally
  pip:
    name={{item}}
    state=latest
    executable=pip3
  with_items:
    - virtualenv
    - bpython
  sudo: yes

- name: Determine if java is installed. Only install java if it hasn't been installed yet
  command: dpkg-query -l java
  register: java_check
  ignore_errors: yes

- name: Add Java PPA
  apt_repository:
    repo='ppa:webupd8team/java'
    state=present
    update_cache=yes
  sudo: yes
  when: java_check.stderr.find('no packages found')

- name: Approve Oracle licesne
  debconf:
    name=oracle-java8-installer
    question=shared/accepted-oracle-license-v1-1
    value=true
    vtype=select
  sudo: yes
  when: java_check.stderr.find('no packages found')

- name: Install Java
  apt:
    name=oracle-java8-installer
    state=latest
  sudo: yes
  when: java_check.stderr.find('no packages found')

- name: Check if PyCharm installed
  stat: path=/opt/jetbrains/pycharm-{{pycharm_version}}/bin/pycharm.sh
  register: pycharm_check

- name: Create PyCharm installation directory
  file:
    path=/opt/jetbrains
    state=directory
  sudo: yes
  when: not pycharm_check.stat.exists

- name: Download PyCharm installer
  get_url:
    url=https://download.jetbrains.com/python/pycharm-professional-{{pycharm_version}}.tar.gz
    dest=/tmp
  when: not pycharm_check.stat.exists

- name: Extract PyCharm tar.gz
  unarchive:
    src=/tmp/pycharm-professional-{{pycharm_version}}.tar.gz
    dest=/opt/jetbrains
    copy=no
  sudo: yes
  when: not pycharm_check.stat.exists

