---
# Install python development tools

- name: Install python related packages
  apt:
    name={{item}}
    state=latest
  with_items:
    - python-dev
    - python3-dev
    - libffi-dev # To build bpython dependencies
  become: yes

- name: Download get-pip script
  get_url:
    url=https://bootstrap.pypa.io/get-pip.py
    dest=/tmp/get-pip.py

- name: Install pip2
  command: python2 /tmp/get-pip.py
  become: yes

- name: Install pip3
  command: python3 /tmp/get-pip.py
  become: yes

- name: Install some python2 modules globally
  pip:
    name={{item}}
    state=latest
    executable=pip2
  with_items:
    - virtualenv
    - bpython
    - ipython
    - virtualenvwrapper
    - flake8
    - tox
    - cookiecutter
    - yapf
  become: yes

- name: Install some python3 modules globally
  pip:
    name={{item}}
    state=latest
    executable=pip3
  with_items:
    - virtualenv
    - bpython
  become: yes

- name: Check if PyCharm installed
  stat: path=/opt/jetbrains/pycharm-{{pycharm_version}}/bin/pycharm.sh
  register: pycharm_check

- name: Create PyCharm installation directory
  file:
    path=/opt/jetbrains
    state=directory
  become: yes
  when: not pycharm_check.stat.exists

- name: Download PyCharm installer
  get_url:
    url=https://download.jetbrains.com/python/pycharm-professional-{{pycharm_version}}.tar.gz
    dest=/tmp
    validate_certs=no
  when: not pycharm_check.stat.exists

- name: Extract PyCharm tar.gz
  unarchive:
    src=/tmp/pycharm-professional-{{pycharm_version}}.tar.gz
    dest=/opt/jetbrains
    copy=no
  become: yes
  when: not pycharm_check.stat.exists

- name: Adding hidpi to pycharm
  lineinfile:
    dest={{item}}
    state=present
    line='-Dhidpi=true'
  become: yes
  with_items:
    - '/opt/jetbrains/pycharm-{{pycharm_version}}/bin/pycharm.vmoptions'
    - '/opt/jetbrains/pycharm-{{pycharm_version}}/bin/pycharm64.vmoptions'
  when: hidpi
