---
# Variables for Linux Laptop installation

change_shell: True
configure_login_manager: True
install_file_sharing_apps: True

# Hardware configuration
install_logitech_c920: yes
lenovo: no
hidpi: yes

screenlayout: personal_linux_desktop.sh

